export default[
    {
        coun_id : 1,
        cus_id: 1,
        date: "2023-09-12",
        time: "오후 2시",
        content: "통화 요청함",
    },
    {
        coun_id : 2,
        cus_id: 1,
        date: "2023-09-16",
        time: "오후 4시",
        content: "미팅 약속을 오전 10시로 변경",
    },
    {
        coun_id : 3,
        cus_id: 1,
        date: "2023-09-19",
        time: "오후 2시",
        content: "청약저축 가입 안내 미팅",
    },
    {
        coun_id : 4,
        cus_id: 2,
        date: "2024-01-15",
        time: "오전 11시",
        content: "방카슈랑스 관심 있으셔서 안내드림",
    },
    {
        coun_id : 5,
        cus_id: 2,
        date: "2024-01-17",
        time: "오후 2시",
        content: "방카 건으로 방문 요청 드림",
    },     
    {
        coun_id : 6,
        cus_id: 3,
        date: "2024-02-17",
        time: "오전 10시",
        content: "12개월 단기납 적금 문의 주심",
    },
    {
        coun_id : 7,
        cus_id: 3,
        date: "2024-02-18",
        time: "오전 11시",
        content: "행복한 적금 상품 안내드리고 브로셔 발송 드림",
    },
    {
        coun_id : 8,
        cus_id: 3,
        date: "2024-02-20",
        time: "오후 3시",
        content: "다음 주 월요일 오전 10시 방문 예정",
    },
    {
        coun_id : 9,
        cus_id: 4,
        date: "2024-03-02",
        time: "오전 11시",
        content: "기존 대출 연장건으로 통화 진행 함.",
    },
    {
        coun_id : 10,
        cus_id: 4,
        date: "2024-03-05",
        time: "오후 1시",
        content: "기 요청건 자격 충족으로 안내드림",
    },  
    {
        coun_id : 11,
        cus_id: 5,
        date: "2024-08-05",
        time: "오전 1시",
        content: "인증서 비밀번호 5회 오류로 재발급 희망하심.",
    },
    {
        coun_id : 12,
        cus_id: 5,
        date: "2024-08-05",
        time: "오후 2시",
        content: "인증서 재발급 처리 완료 함.",
    },
    {
        coun_id : 13,
        cus_id: 6,
        date: "2024-05-06",
        time: "오전 11시",
        content: "어린이 가입 가능 상품 문의 주심",
    },
    {
        coun_id : 14,
        cus_id: 6,
        date: "2024-05-08",
        time: "오후 03시",
        content: "행복만땅 해피어린이 저축 안내드린 후 방문 요청 함.",
    },
    {
        coun_id : 15,
        cus_id: 7,
        date: "2024-02-08",
        time: "오전 10시",
        content: "주소지 변경 요청하여 처리 함.",
    },             
  ]