#MySql 셋팅
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_db
    username: 
    password: 
  sql:
    init:
      mode: never
      # always : 매번, embedded : 내장 DB만, never : 모든 동작 안함
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate :
        show_sql: true
        format_sql: true
server:
  servlet:
    session:
      timeout: 5s
---

spring:
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            clientId: 
            clientSecret: 
            scope:
              - email
              - profile

          naver:
            client-id: 
            client-secret: 
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver  #네이버는 수정가능하나 규칙을 맞추자

          kakao:
            client-id:  # REST API 키
            clientSecret:  # 네이티브 앱 키
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #로그인창 보이기
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me #프로필 정보 받을 곳
            user-name-attribute: response #회원정보를 json으로 받아올 때 response라는 키값으로 리턴.

          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
